### ISSUE TITLE
Kode Register vs Kode Barang

### ISSUE THREAD

**Issue by TheArKaID** [mrizkimaulidan/inven-bs#2]
So, pertama saya agak bingung apa kegunaan Kode Register, ketika saya baca kodenya disebut _register_ , yang membuat saya lebih bingung. Sedangkan Kode Barang mungkin bisa digunakan untuk menspesifikasikan, seperti Kursi milik Ruang Kepala Sekolah dan Kursi milik Ruang Tata Usaha, menjadi _KS-RKS_ dan _KS-RTU_, misalnya.
Nah ketika saya coba untuk print, yang (mungkin) benar tebakan saya itu untuk ditempel ke barangnya, ternyata menggunakan Kode Register. Kenapa tidak menggunakan Kode Barang saja ? Atau, apa yang membedakan Kode Register dan Kode Barang ini ? 
Saya coba memposisikan diri sebagai PJ Sarpras, tapi sepertinya tidak perlu Kode Register, lebih mudah menggunakan dan menggantikannya dengan Kode Barang. Or, I miss something ?

**Comment by mrizkimaulidan** [comment]
Sebenarnya ini proyek dari permintaan tante saya gan kebetulan tante saya orang TU (tata usaha) di sekolah, jadi dari tante saya butuh kolom yang namanya register, saya juga tidak mengerti Kode Register itu untuk apa :laughing:

**Comment by TheArKaID** [comment]
Oh gitu, tantenya emang orang TU berarti ya. Mungkin Kode Register untuk semacam nomor seri yang ada pada barang tersebut sih. 
Eh tapi kenapa di merge coba 😆 Kode Register nya saya hapus.

**Comment by mrizkimaulidan** [comment]
gapapa gan biarin aja, yg di tante saya udah ga saya modifikasi lagi, jadi source code nya saya taruh di github, terima kasih ya!
