### ISSUE TITLE
User role dan hak akses

### ISSUE THREAD

**Issue by mrizkimaulidan** [mrizkimaulidan/inven-bs#36]
Menambahkan fitur role dan permissions untuk membedakan hak akses setiap menu pada aplikasi. Beberapa role yang mungkin akan digunakan:

1. Administrator
- Dashboard
- Data Barang (Import & Excel, Print & Print Individual, Tambah, Lihat, Ubah dan Hapus)
- Data BOS (Tambah, Lihat, Ubah dan Hapus)
- Data Ruangan (Tambah, Lihat, Ubah dan Hapus)
- Data Pengguna (Tambah, Lihat, Ubah dan Hapus)
- Pengaturan Profil

2. Staff TU (Tata Usaha)
- Dashboard
- Data Barang (Import & Excel, Print & Print Individual, Tambah, Lihat, Ubah dan Hapus)
- Data BOS (Tambah, Lihat, Ubah dan Hapus)
- Data Ruangan (Tambah, Lihat, Ubah dan Hapus)
- Pengaturan Profil

**Comment by mrandyyp** [comment]
ijin download ya mas, mau belajr laravel.. keren banget.
